#ifndef TEXT_ERROR_H_
#define TEXT_ERROR_H_

const char* TEXT_PTR_ERROR = "RECEIVED NULL POINTER";
const char* TEXT_SEG_ERROR = "THE INTEGRITY OF THE OBJECT HAS BEEN VIOLATED";
const char* TEXT_SIZE_ERROR = "SIZE AND VOLUME ISSUES";
const char* TEXT_CREATE_ERROR = "NOT INITIALIZED";



#endif // TEXT_ERROR_H_